name: test-pip-install

on:
  push:
    branches:
      - nightly
      - fix-ci
  schedule:
    # minute (0-59)
    # hour (0-23)
    # day of the month (1-31)
    # month (1-12)
    # day of the week (0-6)
    # nightly test at 22:50 UTC time every day
    - cron: "50 22 * * *"

concurrency:
  group: test_pip_install-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_pip_install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install kaldialign
        shell: bash
        run: |
          pip3 install --verbose kaldialign

      - name: Run test
        shell: bash
        run: |
          cd tests
          python3 -c "import kaldialign; print(kaldialign.__file__)"
          python3 -c "import kaldialign; print(kaldialign.__version__)"

          python3 ./test_align.py
